'use client';
import { ArrowDown, ArrowUpRight, Command, Layers, Monitor, Sparkles, ShieldCheck } from 'lucide-react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
const appearances = [
  { id: 'cove-light', name: 'Cove', copy: 'A dark edge that makes the whole desktop feel connected.' },
  { id: 'typeset-light', name: 'Typeset', copy: 'Crisp type, warm highlights, and a little terminal character.' },
  { id: 'porcelain-light', name: 'Porcelain', copy: 'A bright, composed surface with room to breathe.' },
  { id: 'nativeGlass-dark', name: 'Native Glass', copy: 'System-aware materials that feel at home on your Mac.' },
  { id: 'nativeStudio-light', name: 'Native Studio', copy: 'A quieter native appearance for a focused workspace.' },
];
const panels = [
  { id: 'system', name: 'System', title: 'Know what your Mac is doing.', copy: 'CPU, memory, network history, and top processes. Open the details without losing your place.', meta: 'Live metrics · Three history windows' },
  { id: 'nowPlaying', name: 'Music', title: 'Keep the soundtrack close.', copy: 'Control Apple Music, seek through a track, and see what’s playing. Automation access is requested only when you enable it.', meta: 'Apple Music · Playback controls' },
  { id: 'calendar', name: 'Calendar', title: 'Your next thing, at a glance.', copy: 'Browse the calendars already on your Mac, look through your day, and open meeting links. Your events stay read-only.', meta: 'Apple Calendar accounts · Opt-in access' },
  { id: 'audio', name: 'Audio', title: 'From speakers to headphones.', copy: 'Switch input and output devices. Adjust volume and mute when your audio hardware supports it.', meta: 'Core Audio · Device-aware controls' },
  { id: 'vpn', name: 'VPN', title: 'See your connections clearly.', copy: 'Keep configured macOS VPN services and Tailscale in view, with separate connection states and supported controls.', meta: 'macOS services · Optional Tailscale CLI' },
];
export default function Home() {
return <>
<a className="skip-link" href="#main">Skip to content</a>
<header className="site-header wrap"><a className="wordmark" href="#" aria-label="ConstellationBar home"><span className="brand-mark" aria-hidden="true">✳</span> constellation<span className="wordmark-bar">bar</span></a><nav aria-label="Main navigation"><a href="#experience">Explore</a><a href="#appearances">Appearances</a><a className="nav-alpha" href="#alpha">Download alpha <ArrowUpRight size={15}/></a></nav></header>
<main id="main">
<section className="hero wrap"><div className="eyebrow"><span className="status-dot"/> A NEW POINT OF VIEW FOR macOS</div><div className="hero-heading"><h1>Your desktop.<br/><span>In constellation.</span></h1><div className="hero-aside"><p>Workspaces, music, and the little things you check all day. Together in one native Mac bar.</p><a className="primary-link" href="#experience">Take a closer look <ArrowDown size={18}/></a><p className="fine-print">macOS 14+ · Built with Swift & AppKit</p></div></div><div className="hero-product"><div className="product-caption"><span><Command size={14}/> YOUR WORKSPACE, CONNECTED</span><span>01 — COVE / THREE COMPOSITIONS</span></div><img src="/previews/cove-light-board.png" alt="Native ConstellationBar preview showing Rail, Islands and Compact layouts with workspaces and status widgets" width="2880" height="1300" fetchPriority="high"/><div className="product-foot"><span>Quiet at a glance. Useful up close.</span><span>Native app preview · Sample data</span></div></div><div className="principles"><span><Layers/> 3 compositions</span><span><Sparkles/> 5 appearances</span><span><Monitor/> Made for your displays</span><span><ShieldCheck/> No app telemetry</span></div></section>
<section id="experience" className="experience wrap section-space"><div className="section-heading"><div><span className="eyebrow">01 / WITHIN REACH</span><h2>A glance becomes<br/>a little more.</h2></div><p>Hover to look. Click to pin. The same panel stays with you while you get things done.</p></div><Tabs defaultValue="system" className="feature-tabs"><TabsList className="tab-row" aria-label="Explore widget panels">{panels.map(panel => <TabsTrigger key={panel.id} value={panel.id}>{panel.name}</TabsTrigger>)}</TabsList>{panels.map((panel, index) => <TabsContent key={panel.id} value={panel.id} className="feature-panel"><div className="feature-copy"><span className="feature-number">0{index+1}</span><h3>{panel.title}</h3><p>{panel.copy}</p><span className="feature-meta">{panel.meta}</span></div><figure><img src={`/previews/mini-app-${panel.id}.png`} alt={`${panel.name} panel rendered by the native Mac app with sample data`} width="1080" height="1240" loading="lazy"/><figcaption>Native app render with sample data. Glass uses an opaque preview fallback.</figcaption></figure></TabsContent>)}</Tabs></section>
<section id="appearances" className="appearances section-space"><div className="wrap"><div className="section-heading"><div><span className="eyebrow">02 / MAKE IT YOURS</span><h2>One bar.<br/>Your kind of desktop.</h2></div><p>Choose Rail, Islands, or Compact. Pair it with an appearance that feels like you.</p></div><Tabs defaultValue="cove-light"><TabsList className="tab-row" aria-label="Explore appearances">{appearances.map(style => <TabsTrigger key={style.id} value={style.id}>{style.name}</TabsTrigger>)}</TabsList>{appearances.map(style => <TabsContent key={style.id} value={style.id}><div className="appearance-image"><img src={`/previews/${style.id}-board.png`} alt={`${style.name} appearance showing all three bar compositions`} width="2880" height="1300" loading="lazy"/></div><p className="appearance-caption">{style.copy}</p></TabsContent>)}</Tabs></div></section>
<section className="details wrap section-space"><div><span className="eyebrow">03 / YOUR WAY OF WORKING</span><h2>Everything has<br/>its place.</h2></div><div className="detail-list"><article><span>01</span><div><h3>Workspaces, connected.</h3><p>Connect AeroSpace for workspace switching and application-card previews. Use standalone mode for the active app and system widgets.</p></div></article><article><span>02</span><div><h3>A setup for every screen.</h3><p>Give each display its own widgets and workspace buttons. Keep a clock or music in the center of a wide screen, with system status at the edge.</p></div></article><article><span>03</span><div><h3>Only the connections you choose.</h3><p>Calendar and Music access are opt-in. Weather calls Open-Meteo only when configured and enabled. The app collects no telemetry.</p></div></article><article><span>04</span><div><h3>A little more experimental.</h3><p>Optional Codex activity shows persisted task status locally and on connected SSH hosts. A developer-installed browser companion adds media controls. Both are experimental in the alpha.</p></div></article></div></section>
<section id="alpha" className="alpha wrap"><div><span className="eyebrow"><span className="status-dot"/> PUBLIC ALPHA · 0.5.0</span><h2>A better view.<br/>Ready to try.</h2><p>Download the native Mac app, move it to Applications, and make it yours. Developer ID signed and notarized by Apple.</p><a className="primary-link" href="https://github.com/edrenck/constellation-bar/releases/download/v0.5.0/ConstellationBar-0.5.0-universal.zip">Download for Mac <ArrowDown size={18}/></a><p><a href="https://github.com/edrenck/constellation-bar/releases/tag/v0.5.0">Release notes &amp; checksums <ArrowUpRight size={14}/></a></p></div><aside><h3>Before you try it</h3><ul><li>Targets macOS 14 and later</li><li>Universal build for Apple Silicon and Intel</li><li>AeroSpace is optional</li><li>Early software: expect rough edges</li></ul><p>Tested on macOS 27 with Apple Silicon. Intel, older macOS versions and physical multi-monitor setups need alpha feedback.</p><p><a href="https://github.com/edrenck/constellation-bar">Open source under MIT <ArrowUpRight size={14}/></a></p></aside></section>
</main><footer className="wrap"><a className="wordmark" href="#"><span className="brand-mark" aria-hidden="true">✳</span> constellation<span className="wordmark-bar">bar</span></a><span>Made for the way you Mac.</span><a href="#alpha">Download alpha <ArrowUpRight size={14}/></a></footer>
</>;
}
